version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./myapp/:/usr/src/app/
    ports:
      - "8080:8080"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_db

volumes:
  postgres_data:
