# Generated by Django 3.2.10 on 2023-12-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'default_related_name': 'orders', 'verbose_name': 'Ордер', 'verbose_name_plural': 'Ордер'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.IntegerField(blank=True, max_length=25, verbose_name='Значение скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stripe_pay.discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='items', to='stripe_pay.Item', verbose_name='Список элементов'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stripe_pay.tax', verbose_name='Налог'),
        ),
    ]
