# Generated by Django 3.2.10 on 2023-12-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_pay', '0003_auto_20231226_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.FloatField(max_length=15, verbose_name='Значение скидки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'Рубли'), ('usd', 'Доллары')], default='usd', max_length=5, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(max_length=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('rub', 'Рубли'), ('usd', 'Доллары')], default='usd', max_length=10, verbose_name='Валюта'),
        ),
    ]
