# Generated by Django 3.2.10 on 2023-12-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_pay', '0005_alter_tax_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='percent',
            field=models.IntegerField(default=20),
        ),
    ]
