# Generated by Django 3.2.10 on 2023-12-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_pay', '0007_auto_20231226_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.FloatField(max_length=15, verbose_name='Значение скидки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(max_length=15, verbose_name='Цена'),
        ),
    ]
