# Generated by Django 3.2.10 on 2023-12-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_pay', '0004_auto_20231226_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='percent',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
