# Generated by Django 3.2.10 on 2023-12-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_pay', '0008_auto_20231226_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.IntegerField(blank=True, verbose_name='Значение скидки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
